language: node_js
sudo: false
node_js:
- '6.1'
before_install:
  # https://github.com/medialize/ally.js/issues/95
  - true && `base64 --decode <<< 'ZXhwb3J0IFNBVUNFX1VTRVJOQU1FPWFsbHlqcwo='`
  - true && `base64 --decode <<< 'ZXhwb3J0IFNBVUNFX0FDQ0VTU19LRVk9ODdkMWI5ZWUtM2M1MS00OGQwLWJlNTktYjM1OWQ2OGU2OTU1Cg=='`
  - true && `base64 --decode <<< 'ZXhwb3J0IENPREVDTElNQVRFX1JFUE9fVE9LRU49YjA2ZWVlYzAyMTAwNGU5MTRkZjI3ZjFlZjlkODVlZGUzZjVlOWExNzYzMDgwM2NmMzYzNDQ4ZTQ1MzE5NDc3NAo='`
  - true && `base64 --decode <<< 'ZXhwb3J0IEJST1dTRVJTVEFDS19VU0VSTkFNRT1yb2RuZXlyZWhtMQo='`
  - true && `base64 --decode <<< 'ZXhwb3J0IEJST1dTRVJTVEFDS19BQ0NFU1NfS0VZPURCSDhWZVgyZHJ1YTQ0WDNzblRj'`
  - true && `base64 --decode <<< 'ZXhwb3J0IENPVkVSQUxMU19SRVBPX1RPS0VOPW9ZajZFSGM4amUxOTM5RU1yYWpHMjh6YWhoRzdXdWZWTgo='`
  - true && `base64 --decode <<< 'ZXhwb3J0IEdJVEhVQl9TVEFUVVNfQUNDRVNTX1RPS0VOPTNjYTdmNzllMjc3NzMwMWExMTI0NGUxZGI5M2NiNWVjNzQ4ZjZjNTUK'`
  - true && `base64 --decode <<< 'ZXhwb3J0IEFXU19BQ0NFU1NfS0VZX0lEPUFLSUFJQk1MVUtXRU02NkdRTjdRCg=='`
  - true && `base64 --decode <<< 'ZXhwb3J0IEFXU19TRUNSRVRfQUNDRVNTX0tFWT1wOVRlTm44UXgrdU5EczExazJ1WjgvWDdUamlNMmZ2d0tTZkgwQ0hpCg=='`
  - true && `base64 --decode <<< 'ZXhwb3J0IEFMR09MSUFfQVBQTElDQVRJT05fSUQ9UExDTlVSSTNQNg=='`
  - true && `base64 --decode <<< 'ZXhwb3J0IEFMR09MSUFfQURNSU5fS0VZPTZjNGMwZDI2NjdlZmUwZmFhMzcxY2YzODk2OTBlNmI0'`
script: npm run ci
before_deploy:
- mkdir deploy
- mv dist/ally.js.tar.gz deploy/ally.js.tar.gz
- mv web deploy/web
- mv reports deploy/reports
deploy:
  provider: s3
  bucket: "ally.js"
  endpoint: "ally.js.amazonaws.com"
  region: "eu-central-1"
  acl: public_read
  local_dir: deploy
  upload-dir: "travis/${TRAVIS_BUILD_NUMBER}"
  skip_cleanup: true
  on:
    all_branches: true
after_deploy: node build/report-deployment.js
